name: "ecotwitt2mqtt"
version: "latest"
slug: "ecotwitt2mqtt"
description: >-
  "`ecowitt2mqtt` is a small CLI/web server that can receive data from Fine Offset weather stations (and their numerous white-labeled counterparts, like Ecowitt and Ambient Weather), adjust that data in numerous ways, and send it on to one or more MQTT brokers.
arch:
  - armhf
  - amd64
ports:
  8080/tcp: 8080
ports_description:
  - 8485/tcp": "tcp-listen port"
image: "bachya/ecowitt2mqtt"
service:
  - "mqtt:need"
options:
  mqtt:
    - server: "mqtt://core-mosquitto:1883"
shema:
  mqtt:
    - server: "str?",
    - ca: "str?",
    - key: "str?",
    - cert: "str?",
    - user: "str?",
    - password: "str?"
